// @ts-check
import js from '@eslint/js';
import nextPlugin from '@next/eslint-plugin-next';
import prettier from 'eslint-config-prettier/flat';
import reactHooks from 'eslint-plugin-react-hooks';
import globals from 'globals';
import tseslint from 'typescript-eslint';

/**
 * One config for the whole monorepo. Formatting belongs to Prettier; this is
 * for bugs.
 *
 * Production TypeScript is linted with type information, mainly for
 * no-floating-promises and no-misused-promises: an order call that is not
 * awaited is the kind of bug that loses money quietly. Tests and config files
 * sit outside every tsconfig (they are excluded from the build), so they get
 * the same rules without the type-aware ones.
 */
const UNTYPED_TS = ['**/*.test.ts', '**/vitest.config.ts', 'apps/web/next.config.ts'];

export default tseslint.config(
  {
    ignores: ['**/node_modules/', '**/dist/', '**/.next/', '**/.turbo/', '**/coverage/', 'data/',
      // Generated by Next.js.
      'apps/web/next-env.d.ts',
    ],
  },

  js.configs.recommended,

  {
    files: ['**/*.{ts,tsx}'],
    extends: [tseslint.configs.recommendedTypeChecked],
    languageOptions: {
      parserOptions: { projectService: true, tsconfigRootDir: import.meta.dirname },
    },
    rules: {
      // `_`-prefixed names are deliberately unused (placeholders, destructuring).
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrors: 'none' },
      ],
      // Event handlers and Nest lifecycle hooks may be async; a promise
      // returned where void is expected is fine there, not in conditionals.
      '@typescript-eslint/no-misused-promises': ['error', { checksVoidReturn: { attributes: false } }],
      // Off on purpose. Adapters implement a Promise-returning port, and some
      // (paper, fakes) have nothing to await. Dropping `async` to satisfy this
      // would turn a thrown error into a synchronous throw instead of a
      // rejection, which callers do not expect.
      '@typescript-eslint/require-await': 'off',
    },
  },

  {
    files: UNTYPED_TS,
    extends: [tseslint.configs.disableTypeChecked],
  },

  {
    files: ['apps/web/**/*.{ts,tsx}'],
    plugins: { '@next/next': nextPlugin, 'react-hooks': reactHooks },
    rules: {
      ...nextPlugin.configs.recommended.rules,
      ...nextPlugin.configs['core-web-vitals'].rules,
      ...reactHooks.configs.recommended.rules,
    },
    settings: { next: { rootDir: 'apps/web' } },
  },

  {
    files: ['**/*.{js,mjs,cjs}'],
    languageOptions: { globals: globals.node },
  },

  // Last, so it switches off any stylistic rule Prettier owns.
  prettier,
);
