/**
 * EXPERIMENT-009's universe exclusions, frozen on 2026-10-06 and copied from
 * the protocol's Appendix A (docs/EXPERIMENT-009-any-crypto.md).
 */

/** Binance USDT pairs: stablecoins, fiat, gold, wrapped or staked (31). */
export const BINANCE_NOT_CRYPTO_EXPOSURE = [
  'AEUR',
  'AUD',
  'BETH',
  'BFUSD',
  'BKRW',
  'BNSOL',
  'BUSD',
  'DAI',
  'EUR',
  'EURI',
  'FDUSD',
  'FRAX',
  'GBP',
  'PAX',
  'PAXG',
  'RLUSD',
  'SUSD',
  'TUSD',
  'USD1',
  'USDC',
  'USDE',
  'USDP',
  'USDS',
  'USDSB',
  'USDSOLD',
  'UST',
  'USTC',
  'WBETH',
  'WBTC',
  'XAUT',
  'XUSD',
] as const;

/** Binance leveraged tokens (50). */
export const BINANCE_LEVERAGED = [
  '1INCHDOWN',
  '1INCHUP',
  'AAVEDOWN',
  'AAVEUP',
  'ADADOWN',
  'ADAUP',
  'BCHDOWN',
  'BCHUP',
  'BEAR',
  'BNBBEAR',
  'BNBBULL',
  'BNBDOWN',
  'BNBUP',
  'BTCDOWN',
  'BTCUP',
  'BULL',
  'DOTDOWN',
  'DOTUP',
  'EOSBEAR',
  'EOSBULL',
  'EOSDOWN',
  'EOSUP',
  'ETHBEAR',
  'ETHBULL',
  'ETHDOWN',
  'ETHUP',
  'FILDOWN',
  'FILUP',
  'LINKDOWN',
  'LINKUP',
  'LTCDOWN',
  'LTCUP',
  'SUSHIDOWN',
  'SUSHIUP',
  'SXPDOWN',
  'SXPUP',
  'TRXDOWN',
  'TRXUP',
  'UNIDOWN',
  'UNIUP',
  'XLMDOWN',
  'XLMUP',
  'XRPBEAR',
  'XRPBULL',
  'XRPDOWN',
  'XRPUP',
  'XTZDOWN',
  'XTZUP',
  'YFIDOWN',
  'YFIUP',
] as const;

/** Binance tokenized stocks listed from June 2026 (87). */
export const BINANCE_TOKENIZED_STOCKS = [
  'AAOIB',
  'AAPLB',
  'ADBEB',
  'AGPUB',
  'ALABB',
  'AMATB',
  'AMCB',
  'AMDB',
  'AMZNB',
  'ARMB',
  'ASMLB',
  'ASTSB',
  'AVGOB',
  'AXTIB',
  'BABAB',
  'BEB',
  'BMNRB',
  'BNCB',
  'CBRSB',
  'COHRB',
  'COINB',
  'CRCLB',
  'CRDOB',
  'CRMB',
  'CRWDB',
  'CRWVB',
  'CYPHB',
  'DELLB',
  'DJTB',
  'DRAMB',
  'EWYB',
  'FLNCB',
  'FWDIB',
  'GLWB',
  'GMEB',
  'GOOGLB',
  'GPROB',
  'GSB',
  'HIMSB',
  'HOODB',
  'HPEB',
  'IBMB',
  'INTCB',
  'INTWB',
  'IRENB',
  'KORUB',
  'LITEB',
  'METAB',
  'MRNAB',
  'MRVLB',
  'MSFTB',
  'MSTRB',
  'MUB',
  'MUUB',
  'MVLLB',
  'NBISB',
  'NFLXB',
  'NOKB',
  'NVDAB',
  'ORCLB',
  'PDDB',
  'PLTRB',
  'PYPLB',
  'QCOMB',
  'QNTB',
  'QQQB',
  'RDDTB',
  'RKLBB',
  'SHAZB',
  'SKHYB',
  'SMCIB',
  'SMHB',
  'SNDKB',
  'SNXXB',
  'SOXLB',
  'SOXSB',
  'SPCXB',
  'SPYB',
  'SQQQB',
  'STXB',
  'TQQQB',
  'TSLAB',
  'TSMB',
  'USARB',
  'WDCB',
  'WENB',
  'ZMB',
] as const;

/** Binance USDT pairs EXPERIMENT-009 excludes, as symbols. */
export const BINANCE_EXCLUDED: ReadonlySet<string> = new Set(
  [...BINANCE_NOT_CRYPTO_EXPOSURE, ...BINANCE_LEVERAGED, ...BINANCE_TOKENIZED_STOCKS].map(
    (b) => `${b}USDT`,
  ),
);

/** Coinbase USD products EXPERIMENT-009 excludes: stablecoins, gold, staked, a wrapped duplicate. */
export const COINBASE_EXCLUDED: ReadonlySet<string> = new Set([
  'DAI-USD',
  'PAX-USD',
  'USD1-USD',
  'USDS-USD',
  'USDT-USD',
  'PAXG-USD',
  'CBETH-USD',
  'LSETH-USD',
  'MSOL-USD',
  'JITOSOL-USD',
  'WAXL-USD',
]);
